### ISSUE TITLE
*.jobs.yml inline authentication for a workload identity federation Service Connection / Service Principle

### ISSUE THREAD

**Issue by darrenFrowen** [Azure/DevOps-Self-Hosted#43]
**Is your feature request related to a problem? Please describe.**

We have migrated (Converted existing) Service Connection to a workload identity federation Service Connection / Service Principle. Now the inline script authentication is failing as there is no longer a Service Principle secret. 

**Describe the solution you'd like**

Would you by any chance have a working replacement for the following inline authentication for a converted Service Connection workload identity federation?

                inlineScript: |
                  # Log into Az-PowerShell context
                  . $profile # Load PS-Profile configuration
                  $SecuredPassword = ConvertTo-SecureString -AsPlainText -String $env:servicePrincipalKey
                  $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $env:servicePrincipalId, $SecuredPassword
                  $null = Connect-AzAccount -ServicePrincipal -TenantId $env:tenantId -Credential $Credential

**Describe alternatives you've considered**

**Additional context**

**Comment by AlexanderSehr** [comment]
Good day @darrenFrowen,
please excluse the late reply. The last week was pretty travel-intensive.
Introducing OIDC fundamentally makes sense and would be great next update for the solution, so I'll definitely try to take a look at this asap. Figuring out the login will become an interesting challenge.
If of interest: The background of this snippet is, that the logic runs both Azure-PowerShell & AzureCLI commands which both need to be authenticated. As using an Azure-PowerShell task and then loggin into the Azure CLI proofed to be quite difficult (back then), the alternative, that is, an Azure CLI task that also logs into Azure PowerShell was a lot easier.
I'll try to work in this as soon as I can - but if it turns out to not be possible / adjust to OIDC, solving it may take a bit more time as it may ultimately require a rework of parts of the solution.

**Comment by darrenFrowen** [comment]
Thank you @AlexanderSehr for your response I appreciate you are very busy so any support on this matter would be greatly appreciated.

**Comment by AlexanderSehr** [comment]
Hey @darrenFrowen,
good news. After a lot of reading & trial and error I found a good and easy solution. To put it simply - it should be enough to replace all occurences of 
```pwsh
# Log into Az-PowerShell context
. $profile # Load PS-Profile configuration
$SecuredPassword = ConvertTo-SecureString -AsPlainText -String $env:servicePrincipalKey
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $env:servicePrincipalId, $SecuredPassword
$null = Connect-AzAccount -ServicePrincipal -TenantId $env:tenantId -Credential $Credential
```
with 
```pwsh
# Load PS-Profile configuration
. $profile

# Login to Azure-Powershell context
$null = Connect-AzAccount -ApplicationId $env:servicePrincipalId -Tenant $env:tenantId -FederatedToken $env:idToken
```
in the workflows - considering you have set OIDC up correctly.

I tested already the image build part of the solution using a managed identity with a federated credential. The identity has the permissions 'Contributor' & 'Role Based Access Control Administrator'.

I'll make sure to test the rest of the solution too - and then prepare a new release 8.0.0 with all the required updates to the docs etc. which I'll tie to this issue.

In the meantime, please let me know if you encounter any issues :)

**Comment by darrenFrowen** [comment]
Wow thank you so much. Please give me time to test and let me get back you 🙏

**Comment by darrenFrowen** [comment]
Hi @AlexanderSehr ,

Performed the changes as you instructed and the Image builder (Only Storage & Image) that i ran, runs through fine now so thank you for that very much appreciated. The only thing that is confusing me now is that i do not see any new  image version, have i ran this correctly, i see the new image template fine? Apologies in advance its the first time i have looked this since it was handed over back in 2022.
![Image](https://github.com/user-attachments/assets/f2a6c285-dc5e-4727-8c96-e2431d56289c)

**Comment by AlexanderSehr** [comment]
Hey @darrenFrowen,
please note that I release the new version  [8.0.0](https://github.com/Azure/DevOps-Self-Hosted/releases/tag/8.0.0) alongside updated documentation for e.g., OIDC in general ([ref](https://github.com/Azure/DevOps-Self-Hosted/wiki/OIDC)) and the indiviaual constructs in particular.

**Comment by AlexanderSehr** [comment]
> Hi [@AlexanderSehr](https://github.com/AlexanderSehr) ,
> 
> Performed the changes as you instructed and the Image builder (Only Storage & Image) that i ran, runs through fine now so thank you for that very much appreciated. The only thing that is confusing me now is that i do not see any new image version, have i ran this correctly, i see the new image template fine? Apologies in advance its the first time i have looked this since it was handed over back in 2022. ![Image](https://github.com/user-attachments/assets/f2a6c285-dc5e-4727-8c96-e2431d56289c)

Overlooked the comment. Sorry @darrenFrowen.

Regarding your question I can at least say (🥁) it worked for me 🎊 

But joeks aside - It should work. There are a few things to check
- On the ImageTemplate resource does it show a status that would imply it ran?
- When running the pipeline, was it configured so that it would actually trigger the run?
- In the Infrastructure resource group (the one the Image Template deploys its resources in), do you see a Storage Account (which would imply that the template did run) and or active resources (which would imply it does currently run). If not, then it's likely that the image template was either not triggered or failed before even starting - which woulb be visible on the image template itself.

The change to OIDC should not have an effect on how the logic works - just on who it is run by.

**Comment by AlexanderSehr** [comment]
> Hi [@AlexanderSehr](https://github.com/AlexanderSehr) ,
> 
> Thank you for your great support. Update the Image template had failed to build so manually ran that and we now have the new image version.
> 
> ![Image](https://github.com/user-attachments/assets/651bb1d2-fb64-4c22-a97a-9fc79c91e7fe)
> 
> The only thing now is how do i know the scaleset are using the new version?
> 
> Is this all the confirmation i need?
> 
> ![Image](https://github.com/user-attachments/assets/8b208279-0d73-46e6-aed6-229c8c1f7d25)

Great question - and I'm unfortuantely not entirely sure. The [docs](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set#how-to-update-global-scale-set-properties) in that regard do not specify what 'latest' actually means (i.e., if it includes the image version). What I tended to do was to actually remove the active agents once and have the scale set just spin up new instances.

That being said - if you ever happen to find the answer, please let me know 😄 

> Sidenote:
> With the new 'Managed Agent Pool' resource this becomes a bit easier as it actually tells you which image version runs on which instance  ![Image](https://github.com/user-attachments/assets/80dcf95e-f3cd-4489-b8ae-d531b5ce29db)

**Comment by AlexanderSehr** [comment]
> Hi Alexander,
> 
> I decided to delete the scale set and attempt to deploy new to ensure they picked up the new image version, small issue at first where the pipeline referenced what looked to be an old variable name '.variables.vmssParam.namehad' needed changing to var '.variables.vmssWindowsParam.name' as per '.scaleset.bicep' variable. This ran and scale set was deployed correctly.
> 
> I then hit an issue where the agents weren't picking up the deployment job, realised you need to check the register/update agent pool on the pipeline but then ran into the file 'prd.agentpool.config.json hadn't any Org, Project or ServiceConnection defined and ran it again still the same error, apologies for the redaction.
> 
> ![Image](https://github.com/user-attachments/assets/08cb0516-1f3c-4a25-9d36-dd8d134d418d)
> 
> {
>     "Organization": "XXXX-DevOps",
>     "Project": "XXXXX-XXXXX",
>     "ServiceConnectionName": "SC-ADO-MG-Client-XXXXXX_XXX",
>     "AgentPoolProperties": {
>         "ScaleSetPoolName": "agents-uks-xxxxxxx-win-01",
>         "RecycleAfterEachUse": false,
>         "MaxSavedNodeCount": 0,
>         "MaxCapacity": 10,
>         "DesiredIdle": 1,
>         "TimeToLiveMinutes": 15,
>         "AgentInteractiveUI": false,
>         "AuthorizeAllPipelines": true // works only on creation
>     }
> }

Hey @darrenFrowen,
any chance the Build Service of the pipeline does not have the permissions to fetch the Service Connections? This would explain why it is able to find the project, but not the connection endpoint.
If bad comes to worse, you can of course also work around this by creating the Agent Pool manually - though using the automation is of course more comfortable 😉

**Comment by darrenFrowen** [comment]
Hi @AlexanderSehr,

Indeed on the latter and the former I'll check tomorrow, thank you once more.

**Comment by darrenFrowen** [comment]
Hi @AlexanderSehr ,

I couldn't work out why the Agent Pool update errors out when i check that box, ultimately the pipeline uses the service connection to deploy the scale-set which it had completed.  I then found this in our Wiki that MS handed over hence the reason the json file didnt have the required paramters.

![Image](https://github.com/user-attachments/assets/01140b6c-5e91-4ffd-b2a5-23bad6afae69)

So planned this morning to add manually as you suggested, checked the agent pool this morning and the agents were already there. I can only assume it just took time for them to appear. 

I then proceeded to run my Data Management zone pipelines back on with the self hosted agent pool. This fails with the following. I can only assume that the software build did not complete successfully. 

`[error]The term 'pwsh.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again..`

In the process of building again.

**Comment by AlexanderSehr** [comment]
Hey @darrenFrowen I'm sorry to hear. How about we set up a call some time and troubleshoot it together. I may be able to provide a couple more pointers and address some conceptions. May save you some time too and I'd like to see this working for you 💪

**Comment by darrenFrowen** [comment]
Hi @AlexanderSehr ,

That would be really helpful. And if it helps on your side i have the following tracking ID: 2411190050002715, i reached out on this repo at the same time as i raised the support ticket. Available anytime after 12:00Hrs GMT?

Regards

**Comment by darrenFrowen** [comment]
Hi @AlexanderSehr ,

Further update post the building the image again. This time it passed the pwsh.exe but failed on `Cannot find Bicep`. I found the storage account and downloaded the packer log. The issue appears to be with .NET with hundreds of errors as per the below screenshot. 

![Image](https://github.com/user-attachments/assets/2f636212-b74d-4550-846f-f67e98c1e9ce)

Then if i search on bicep i see this again .NET issue not being installed.

![Image](https://github.com/user-attachments/assets/d88ebc6f-72ec-4def-a799-b4e00acfc4ef)
